apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbinia-api-server
  labels:
    app: turbinia-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbinia-api-server
  template:
    metadata:
      annotations:
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
      labels:
        app: turbinia-api-server
    spec:
      #serviceAccountName: turbinia
      #automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 999
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: redis-probe
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz redis 6379; do echo "Waiting for redis..."; sleep 3; done;']
      containers:
        - name: api
          image: us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-api-server:latest
          env:
            - name: TURBINIA_CONF
              valueFrom:
                configMapKeyRef:
                  name: turbinia-config
                  key: TURBINIA_CONF
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /etc/turbinia
              name: config-volume
            - mountPath: /mnt/turbiniavolume
              name: turbiniavolume
            - mountPath: /var/log
              name: logs
            - mountPath: /var/tmp
              name: tmp
          ports:
            - containerPort: 9200
            - containerPort: 8000
          # resources: 
          #   requests:
          #     memory: "4096Mi"
          #     cpu: "2000m"
          #   limits:
          #     memory: "16384Mi"
          #     cpu: "4000m"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 999
      volumes:
        - name: config-volume
          configMap:
            name: turbinia-config
            items:
            - key: TURBINIA_CONF
              path: turbinia.conf
        - name: turbiniavolume
          persistentVolumeClaim:
            claimName: turbiniavolume-claim
            readOnly: false
        - name: logs
          emptyDir: {}
        - name: tmp
          emptyDir: {}