apiVersion: v1
kind: PersistentVolume
metadata:
  name: criticalvolume
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /criticalvolume
    server: 10.211.209.194  # GCP project:turbiniang-dev
