"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import turbinia_python_client
from turbinia_python_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createrequest_create_evidence_type_post(self):
        """Test case for createrequest_create_evidence_type_post

        Createrequest  # noqa: E501
        """
        pass

    def test_root_get(self):
        """Test case for root_get

        Root  # noqa: E501
        """
        pass

    def test_statusrequest_status_request_request_id_get(self):
        """Test case for statusrequest_status_request_request_id_get

        Statusrequest  # noqa: E501
        """
        pass

    def test_statusrequests_status_requests_get(self):
        """Test case for statusrequests_status_requests_get

        Statusrequests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
