"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import turbinia_python_client
from turbinia_python_client.model.request_options import RequestOptions
globals()['RequestOptions'] = RequestOptions
from turbinia_python_client.model.request import Request


class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequest(self):
        """Test Request"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Request()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
