"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import turbinia_python_client
from turbinia_python_client.model.gcp import GCP
from turbinia_python_client.model.generic import Generic
globals()['GCP'] = GCP
globals()['Generic'] = Generic
from turbinia_python_client.model.request_options import RequestOptions


class TestRequestOptions(unittest.TestCase):
    """RequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestOptions(self):
        """Test RequestOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
