"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import turbinia_python_client
from turbinia_python_client.model.gcp import GCP


class TestGCP(unittest.TestCase):
  """GCP unit test stubs"""

  def setUp(self):
    pass

  def tearDown(self):
    pass

  def testGCP(self):
    """Test GCP"""
    # FIXME: construct object with mandatory attributes with example values
    # model = GCP()  # noqa: E501
    pass


if __name__ == '__main__':
  unittest.main()
